### ISSUE TITLE
Problem on starting the app

### ISSUE THREAD

**Issue by heartquake** [Youscribe/Xamarin.CrossWalk#1]
VS2015 is unable to run this app. I have no idea why but it just don't work.

**Comment by kYann** [comment]
Hi,

Wich App, the Specific Abi app or the Multi Abi App. Also is there any log in the output window ?

**Comment by heartquake** [comment]
Hi,
I'm trying the both. Please see the output.

> Android application is debugging.
> Couldn't connect to logcat, GetProcessId returned: 0
> Loaded assembly: /storage/emulated/0/Android/data/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/files/.**override**/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.dll
> Loaded assembly: /storage/emulated/0/Android/data/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/files/.**override**/Java.Interop.dll [External]
> Loaded assembly: /storage/emulated/0/Android/data/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/files/.**override**/Xamarin.Droid.CrossWalkLite.dll
> Loaded assembly: /storage/emulated/0/Android/data/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/files/.**override**/System.ServiceModel.Internals.dll [External]
> Loaded assembly: Mono.Android.dll
> Loaded assembly: System.dll
> Loaded assembly: System.Core.dll
> Loaded assembly: MonoDroidConstructors [External]

**Comment by heartquake** [comment]
App is starting but exiting immediately.

**Comment by heartquake** [comment]
And here's the device log.

> 10-27 13:20:46.088 D/DhcpClient(  484): Received packet: 00:23:7d:52:0c:41 ACK: your new IP /0.0.0.0, netmask /255.255.252.0, gateway /10.106.0.1 DNS servers: /10.10.0.3 /10.10.0.5 , lease time null
> 10-27 13:21:07.614 D/AndroidRuntime( 1620): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
> 10-27 13:21:07.615 D/AndroidRuntime( 1620): CheckJNI is OFF
> 10-27 13:21:07.615 E/cutils-trace( 1620): Error opening trace file: No such file or directory (2)
> 10-27 13:21:07.624 D/ICU     ( 1620): No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
> 10-27 13:21:07.638 E/memtrack( 1620): Couldn't load memtrack module (No such file or directory)
> 10-27 13:21:07.638 E/android.os.Debug( 1620): failed to load memtrack module: -2
> 10-27 13:21:07.639 I/Radio-JNI( 1620): register_android_hardware_Radio DONE
> 10-27 13:21:07.646 D/AndroidRuntime( 1620): Calling main entry com.android.commands.am.Am
> 10-27 13:21:07.649 D/AndroidRuntime( 1620): Shutting down VM
> 10-27 13:21:07.991 D/AndroidRuntime( 1632): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
> 10-27 13:21:07.992 D/AndroidRuntime( 1632): CheckJNI is OFF
> 10-27 13:21:07.992 E/cutils-trace( 1632): Error opening trace file: No such file or directory (2)
> 10-27 13:21:08.001 D/AndroidRuntime( 1633): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
> 10-27 13:21:08.002 D/AndroidRuntime( 1633): CheckJNI is OFF
> 10-27 13:21:08.002 E/cutils-trace( 1633): Error opening trace file: No such file or directory (2)
> 10-27 13:21:08.002 D/ICU     ( 1632): No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
> 10-27 13:21:08.012 D/ICU     ( 1633): No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
> 10-27 13:21:08.019 E/memtrack( 1632): Couldn't load memtrack module (No such file or directory)
> 10-27 13:21:08.019 E/android.os.Debug( 1632): failed to load memtrack module: -2
> 10-27 13:21:08.020 I/Radio-JNI( 1632): register_android_hardware_Radio DONE
> 10-27 13:21:08.026 E/memtrack( 1633): Couldn't load memtrack module (No such file or directory)
> 10-27 13:21:08.026 E/android.os.Debug( 1633): failed to load memtrack module: -2
> 10-27 13:21:08.026 D/AndroidRuntime( 1632): Calling main entry com.android.commands.pm.Pm
> 10-27 13:21:08.027 I/Radio-JNI( 1633): register_android_hardware_Radio DONE
> 10-27 13:21:08.028 I/ActivityManager(  484): Force stopping Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp appid=10083 user=-1: uninstall pkg
> 10-27 13:21:08.035 D/AndroidRuntime( 1633): Calling main entry com.android.commands.pm.Pm
> 10-27 13:21:08.068 I/art     (  484): Starting a blocking GC Explicit
> 10-27 13:21:08.077 I/art     (  484): Explicit concurrent mark sweep GC freed 4818(362KB) AllocSpace objects, 3(112KB) LOS objects, 33% free, 5MB/8MB, paused 274us total 9.077ms
> 10-27 13:21:08.080 W/PackageManager(  484): Couldn't remove dex file for package:  at location /data/app/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp-1/base.apk, retcode=-1
> 10-27 13:21:08.081 I/ActivityManager(  484): Force stopping Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp appid=10083 user=-1: uninstall pkg
> 10-27 13:21:08.081 I/art     ( 1632): System.exit called, status: 0
> 10-27 13:21:08.081 I/AndroidRuntime( 1632): VM exiting with result code 0.
> 10-27 13:21:08.093 I/art     (  484): Starting a blocking GC Explicit
> 10-27 13:21:08.103 I/art     (  484): Explicit concurrent mark sweep GC freed 5462(397KB) AllocSpace objects, 2(40KB) LOS objects, 33% free, 5MB/8MB, paused 450us total 9.984ms
> 10-27 13:21:08.104 I/ActivityManager(  484): Force stopping Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp appid=10083 user=0: pkg removed
> 10-27 13:21:08.104 I/art     ( 1633): System.exit called, status: 0
> 10-27 13:21:08.104 I/AndroidRuntime( 1633): VM exiting with result code 0.
> 10-27 13:21:08.109 D/CarrierServiceBindHelper(  857): Receive action: android.intent.action.PACKAGE_REMOVED
> 10-27 13:21:08.109 D/CarrierServiceBindHelper(  857): mHandler: 3
> 10-27 13:21:08.109 D/CarrierConfigLoader(  857): mHandler: 9 phoneId: 0
> 10-27 13:21:08.110 D/JobSchedulerService(  484): Receieved: android.intent.action.PACKAGE_REMOVED
> 10-27 13:21:08.111 I/InputReader(  484): Reconfiguring input devices.  changes=0x00000010
> 10-27 13:21:08.112 W/ContextImpl( 1072): Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1221 android.content.ContextWrapper.startService:581 android.content.ContextWrapper.startService:581 com.android.keychain.KeyChainBroadcastReceiver.onReceive:12 android.app.ActivityThread.handleReceiver:2725 
> 10-27 13:21:08.115 D/Documents( 1287): Update found 6 roots in 7ms
> 10-27 13:21:08.116 I/ActivityManager(  484): Force stopping Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp appid=10083 user=0: pkg removed
> 10-27 13:21:08.119 D/JobSchedulerService(  484): Receieved: android.intent.action.PACKAGE_REMOVED
> 10-27 13:21:08.119 I/InputReader(  484): Reconfiguring input devices.  changes=0x00000010
> 10-27 13:21:08.120 D/CarrierServiceBindHelper(  857): Receive action: android.intent.action.PACKAGE_REMOVED
> 10-27 13:21:08.120 D/Documents( 1287): Update found 6 roots in 0ms
> 10-27 13:21:08.121 D/CarrierServiceBindHelper(  857): mHandler: 3
> 10-27 13:21:08.121 D/CarrierConfigLoader(  857): mHandler: 9 phoneId: 0
> 10-27 13:21:08.124 I/LatinIME:LogUtils(  820): Dictionary info: dictionary = main:en ; version = 54 ; date = 1414726273
> 10-27 13:21:08.126 D/VoicemailCleanupService(  772): Cleaning up data for package: Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp
> 10-27 13:21:08.128 I/LatinIME:LogUtils(  820): Dictionary info: dictionary = main:en ; version = 54 ; date = 1414726273
> 10-27 13:21:08.128 W/ContextImpl( 1072): Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1221 android.content.ContextWrapper.startService:581 android.content.ContextWrapper.startService:581 com.android.keychain.KeyChainBroadcastReceiver.onReceive:12 android.app.ActivityThread.handleReceiver:2725 
> 10-27 13:21:08.143 D/VoicemailCleanupService(  772): Cleaning up data for package: Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp
> 10-27 13:21:10.445 D/AndroidRuntime( 1659): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
> 10-27 13:21:10.446 D/AndroidRuntime( 1659): CheckJNI is OFF
> 10-27 13:21:10.446 E/cutils-trace( 1659): Error opening trace file: No such file or directory (2)
> 10-27 13:21:10.455 D/ICU     ( 1659): No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
> 10-27 13:21:10.465 E/memtrack( 1659): Couldn't load memtrack module (No such file or directory)
> 10-27 13:21:10.465 E/android.os.Debug( 1659): failed to load memtrack module: -2
> 10-27 13:21:10.466 I/Radio-JNI( 1659): register_android_hardware_Radio DONE
> 10-27 13:21:10.472 D/AndroidRuntime( 1659): Calling main entry com.android.commands.pm.Pm
> 10-27 13:21:10.477 D/DefContainer( 1315): Copying /data/local/tmp/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp-Signed.apk to base.apk
> 10-27 13:21:10.764 I/PackageManager.DexOptimizer(  484): Running dexopt (dex2oat) on: /data/app/vmdl2059876374.tmp/base.apk pkg=Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp isa=x86 vmSafeMode=false debuggable=true oatDir = /data/app/vmdl2059876374.tmp/oat
> 10-27 13:21:10.770 W/dex2oat ( 1668): Mismatch between dex2oat instruction set features (ISA: X86 Feature string: smp,-ssse3,-sse4.1,-sse4.2,-avx,-avx2) and those of dex2oat executable (ISA: X86 Feature string: smp,ssse3,-sse4.1,-sse4.2,-avx,-avx2) for the command line:
> 10-27 13:21:10.770 W/dex2oat ( 1668): /system/bin/dex2oat --zip-fd=6 --zip-location=base.apk --oat-fd=7 --oat-location=/data/app/vmdl2059876374.tmp/oat/x86/base.odex --instruction-set=x86 --instruction-set-variant=default --instruction-set-features=default --runtime-arg -Xms64m --runtime-arg -Xmx512m --swap-fd=8 --debuggable
> 10-27 13:21:10.770 I/dex2oat ( 1668): /system/bin/dex2oat --debuggable
> 10-27 13:21:10.771 E/cutils-trace( 1668): Error opening trace file: No such file or directory (2)
> 10-27 13:21:11.198 I/dex2oat ( 1668): dex2oat took 427.945ms (threads: 2) arena alloc=907KB java alloc=2MB native alloc=9MB free=2MB
> 10-27 13:21:11.239 V/BackupManagerService(  484): restoreAtInstall pkg=Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp token=3 restoreSet=0
> 10-27 13:21:11.239 V/BackupManagerService(  484): Finishing install immediately
> 10-27 13:21:11.239 W/Settings(  484): Setting install_non_market_apps has moved from android.provider.Settings.Global to android.provider.Settings.Secure, returning read-only value.
> 10-27 13:21:11.239 I/art     (  484): Starting a blocking GC Explicit
> 10-27 13:21:11.249 I/art     (  484): Explicit concurrent mark sweep GC freed 32705(2MB) AllocSpace objects, 18(336KB) LOS objects, 33% free, 5MB/8MB, paused 174us total 7.615ms
> 10-27 13:21:11.250 I/art     ( 1659): System.exit called, status: 0
> 10-27 13:21:11.250 I/AndroidRuntime( 1659): VM exiting with result code 0.
> 10-27 13:21:11.251 D/CarrierServiceBindHelper(  857): Receive action: android.intent.action.PACKAGE_ADDED
> 10-27 13:21:11.251 D/CarrierServiceBindHelper(  857): mHandler: 3
> 10-27 13:21:11.251 D/CarrierConfigLoader(  857): mHandler: 9 phoneId: 0
> 10-27 13:21:11.253 D/Documents( 1287): Update found 6 roots in 1ms
> 10-27 13:21:11.254 I/InputReader(  484): Reconfiguring input devices.  changes=0x00000010
> 10-27 13:21:11.264 W/VoiceInteractionManagerService(  484): no available voice recognition services found for user 0
> 10-27 13:21:11.903 D/AndroidRuntime( 1688): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
> 10-27 13:21:11.904 D/AndroidRuntime( 1688): CheckJNI is OFF
> 10-27 13:21:11.904 E/cutils-trace( 1688): Error opening trace file: No such file or directory (2)
> 10-27 13:21:11.918 D/ICU     ( 1688): No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
> 10-27 13:21:11.939 E/memtrack( 1688): Couldn't load memtrack module (No such file or directory)
> 10-27 13:21:11.939 E/android.os.Debug( 1688): failed to load memtrack module: -2
> 10-27 13:21:11.939 I/Radio-JNI( 1688): register_android_hardware_Radio DONE
> 10-27 13:21:11.949 D/AndroidRuntime( 1688): Calling main entry com.android.commands.am.Am
> 10-27 13:21:11.953 D/AndroidRuntime( 1688): Shutting down VM
> 10-27 13:21:12.271 D/AndroidRuntime( 1698): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
> 10-27 13:21:12.271 D/AndroidRuntime( 1698): CheckJNI is OFF
> 10-27 13:21:12.272 E/cutils-trace( 1698): Error opening trace file: No such file or directory (2)
> 10-27 13:21:12.280 D/ICU     ( 1698): No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
> 10-27 13:21:12.289 E/memtrack( 1698): Couldn't load memtrack module (No such file or directory)
> 10-27 13:21:12.289 E/android.os.Debug( 1698): failed to load memtrack module: -2
> 10-27 13:21:12.290 I/Radio-JNI( 1698): register_android_hardware_Radio DONE
> 10-27 13:21:12.296 D/AndroidRuntime( 1698): Calling main entry com.android.commands.am.Am
> 10-27 13:21:12.298 I/ActivityManager(  484): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/md5b42667a1c752280fd2e79efbd2128d96.MainActivity} from uid 0 on display 0
> 10-27 13:21:12.301 D/AndroidRuntime( 1698): Shutting down VM
> 10-27 13:21:12.305 I/art     ( 1706): Late-enabling -Xcheck:jni
> 10-27 13:21:12.314 I/ActivityManager(  484): Start proc 1706:Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/u0a83 for activity Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/md5b42667a1c752280fd2e79efbd2128d96.MainActivity
> 10-27 13:21:12.338 W/monodroid( 1706): Using override path: /data/user/0/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/files/.**override**
> 10-27 13:21:12.338 W/monodroid( 1706): Using override path: /storage/emulated/0/Android/data/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/files/.**override**
> 10-27 13:21:12.338 W/monodroid( 1706): Trying to load sgen from: /data/user/0/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/files/.**override**/libmonosgen-2.0.so
> 10-27 13:21:12.338 W/monodroid( 1706): Trying to load sgen from: /storage/emulated/0/Android/data/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/files/.**override**/libmonosgen-2.0.so
> 10-27 13:21:12.338 W/monodroid( 1706): Trying to load sgen from: /data/app/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp-1/lib/x86/libmonosgen-2.0.so
> 10-27 13:21:12.338 W/monodroid( 1706): Trying to load sgen from: /data/user/0/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/files/.**override**/links/libmonosgen-2.0.so
> 10-27 13:21:12.344 W/monodroid-debug( 1706): Trying to initialize the debugger with options: --debugger-agent=transport=dt_socket,loglevel=0,address=127.0.0.1:8805,server=y,embedding=1
> 10-27 13:21:12.398 E/Surface (  870): getSlotFromBufferLocked: unknown buffer: 0xaf631e00
> 10-27 13:21:12.513 W/monodroid-debug( 1706): Accepted stdout connection: 20
> 10-27 13:21:13.270 D/Mono    ( 1706): Image addref mscorlib[0xac16d660] -> mscorlib.dll[0xadaad800]: 1
> 10-27 13:21:13.271 D/Mono    ( 1706): AOT module 'mscorlib.dll.so' not found: dlopen failed: library "/data/app/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp-1/lib/x86/libaot-mscorlib.dll.so" not found
> 10-27 13:21:13.271 D/Mono    ( 1706): AOT module '/Users/builder/data/lanes/3415/7db2aac3/source/monodroid/builds/install/mono-x86/lib/mono/aot-cache/x86/mscorlib.dll.so' not found: dlopen failed: library "/data/app/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp-1/lib/x86/libaot-mscorlib.dll.so" not found
> 10-27 13:21:13.272 D/Mono    ( 1706): Config attempting to parse: 'mscorlib.dll.config'.
> 10-27 13:21:13.272 D/Mono    ( 1706): Config attempting to parse: '/Users/builder/data/lanes/3415/7db2aac3/source/monodroid/builds/install/mono-x86/etc/mono/assemblies/mscorlib/mscorlib.config'.
> 10-27 13:21:13.281 D/Mono    ( 1706): Assembly mscorlib[0xac16d660] added to domain RootDomain, ref_count=1
> 10-27 13:21:13.306 D/Mono    ( 1706): GC_MAJOR: (user request) pause 0.20ms, total 0.20ms, bridge 0.00ms major 208K/0K los 0K/0K
> 10-27 13:21:13.311 D/Mono    ( 1706): Unloading domain RootDomain[0xadab7300], assembly mscorlib[0xac16d660], ref_count=1
> 10-27 13:21:13.311 D/Mono    ( 1706): Unloading assembly mscorlib [0xac16d660].
> 10-27 13:21:13.311 D/Mono    ( 1706): Unloading image mscorlib.dll [0xadaad800].
> 10-27 13:21:13.382 I/ActivityManager(  484): Process Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp (pid 1706) has died
> 10-27 13:21:13.384 I/art     ( 1729): Late-enabling -Xcheck:jni
> 10-27 13:21:13.392 I/ActivityManager(  484): Start proc 1729:Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/u0a83 for activity Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/md5b42667a1c752280fd2e79efbd2128d96.MainActivity
> 10-27 13:21:13.403 W/monodroid( 1729): Using override path: /data/user/0/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/files/.**override**
> 10-27 13:21:13.403 W/monodroid( 1729): Using override path: /storage/emulated/0/Android/data/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/files/.**override**
> 10-27 13:21:13.403 W/monodroid( 1729): Trying to load sgen from: /data/user/0/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/files/.**override**/libmonosgen-2.0.so
> 10-27 13:21:13.403 W/monodroid( 1729): Trying to load sgen from: /storage/emulated/0/Android/data/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/files/.**override**/libmonosgen-2.0.so
> 10-27 13:21:13.403 W/monodroid( 1729): Trying to load sgen from: /data/app/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp-1/lib/x86/libmonosgen-2.0.so
> 10-27 13:21:13.403 W/monodroid( 1729): Trying to load sgen from: /data/user/0/Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/files/.**override**/links/libmonosgen-2.0.so
> 10-27 13:21:13.405 W/monodroid-debug( 1729): Trying to initialize the debugger with options: --debugger-agent=transport=dt_socket,loglevel=0,address=127.0.0.1:8805,server=y,embedding=1
> 10-27 13:21:13.405 W/monodroid-debug( 1729): Accepted stdout connection: -1
> 10-27 13:21:13.405 F/monodroid-debug( 1729): Error accepting stdout and stderr (127.0.0.1:8806): Address already in use
> 10-27 13:21:13.433 D/AndroidRuntime( 1724): >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
> 10-27 13:21:13.434 D/AndroidRuntime( 1724): CheckJNI is OFF
> 10-27 13:21:13.434 E/cutils-trace( 1724): Error opening trace file: No such file or directory (2)
> 10-27 13:21:13.442 D/ICU     ( 1724): No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
> 10-27 13:21:13.448 I/Zygote  (  156): Process 1729 exited cleanly (3)
> 10-27 13:21:13.453 I/ActivityManager(  484): Process Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp (pid 1729) has died
> 10-27 13:21:13.456 I/art     ( 1742): Late-enabling -Xcheck:jni
> 10-27 13:21:13.462 E/memtrack( 1724): Couldn't load memtrack module (No such file or directory)
> 10-27 13:21:13.462 E/android.os.Debug( 1724): failed to load memtrack module: -2
> 10-27 13:21:13.463 I/Radio-JNI( 1724): register_android_hardware_Radio DONE
> 10-27 13:21:13.464 I/ActivityManager(  484): Start proc 1742:Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/u0a83 for activity Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/md5b42667a1c752280fd2e79efbd2128d96.MainActivity
> 10-27 13:21:13.470 D/AndroidRuntime( 1724): Calling main entry com.android.commands.am.Am
> 10-27 13:21:13.470 I/ActivityManager(  484): Force stopping Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp appid=10083 user=0: from pid 1724
> 10-27 13:21:13.470 I/ActivityManager(  484): Killing 1742:Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/u0a83 (adj 0): stop Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp
> 10-27 13:21:13.532 W/ActivityManager(  484): Force removing ActivityRecord{b0566bb u0 Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/md5b42667a1c752280fd2e79efbd2128d96.MainActivity t218}: app died, no saved state
> 10-27 13:21:13.533 W/WindowManager(  484): Failed looking up window
> 10-27 13:21:13.533 W/WindowManager(  484): java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@c6ea6fa does not exist
> 10-27 13:21:13.533 W/WindowManager(  484):  at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8733)
> 10-27 13:21:13.533 W/WindowManager(  484):  at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8724)
> 10-27 13:21:13.533 W/WindowManager(  484):  at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2697)
> 10-27 13:21:13.533 W/WindowManager(  484):  at com.android.server.wm.Session.remove(Session.java:187)
> 10-27 13:21:13.533 W/WindowManager(  484):  at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3099)
> 10-27 13:21:13.533 W/WindowManager(  484):  at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5606)
> 10-27 13:21:13.533 W/WindowManager(  484):  at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3409)
> 10-27 13:21:13.533 W/WindowManager(  484):  at android.os.Handler.dispatchMessage(Handler.java:102)
> 10-27 13:21:13.533 W/WindowManager(  484):  at android.os.Looper.loop(Looper.java:148)
> 10-27 13:21:13.533 W/WindowManager(  484):  at android.os.HandlerThread.run(HandlerThread.java:61)
> 10-27 13:21:13.533 W/WindowManager(  484):  at com.android.server.ServiceThread.run(ServiceThread.java:46)
> 10-27 13:21:13.534 W/ActivityManager(  484): Spurious death for ProcessRecord{d3ec2aa 0:Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp/u0a83}, curProc for 1742: null
> 10-27 13:21:13.535 D/AndroidRuntime( 1724): Shutting down VM
> 10-27 13:21:13.552 W/EGL_emulation(  870): eglSurfaceAttrib not implemented
> 10-27 13:21:13.552 W/OpenGLRenderer(  870): Failed to set EGL_SWAP_BEHAVIOR on surface 0xa463b520, error=EGL_SUCCESS
> 10-27 13:21:13.555 W/InputMethodManagerService(  484): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@c84de9b attribute=null, token = android.os.BinderProxy@c5427ba
> 10-27 13:21:14.079 W/OpenGLRenderer(  870): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
> 10-27 13:21:14.079 W/OpenGLRenderer(  870): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
> 10-27 13:21:21.964 D/DhcpClient(  484): Received packet: 78:ac:c0:b7:ec:c7 ACK: your new IP /0.0.0.0, netmask /255.255.252.0, gateway /10.106.0.1 DNS servers: /10.10.0.3 /10.10.0.5 , lease time null
> 10-27 13:21:29.365 D/DhcpClient(  484): Received packet: 78:ac:c0:b5:72:4a ACK: your new IP /0.0.0.0, netmask /255.255.252.0, gateway /10.106.0.1 DNS servers: /10.10.0.3 /10.10.0.5 , lease time null
> 10-27 13:21:46.659 D/DhcpClient(  484): Received packet: 94:65:9c:0e:56:fa ACK: your new IP /10.106.1.208, netmask /255.255.252.0, gateway /10.106.0.1 DNS servers: /10.10.0.3 /10.10.0.5 , lease time 691200
> 10-27 13:21:53.534 D/DhcpClient(  484): Received packet: 00:21:5a:17:7e:43 ACK: your new IP /10.106.0.208, netmask /255.255.252.0, gateway /10.106.0.1 DNS servers: /10.10.0.3 /10.10.0.5 , lease time 691200

**Comment by shshshdy** [comment]
Same Problem

**Comment by naveeniiitbsr** [comment]
Same problem any solution...?
